version: 2
updates:
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly
      day: saturday
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      allNuGet:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      allGHA:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      allDocker:
        patterns:
          - "*"
