openapi: 3.0.0
servers:
  - url: https://localhost:7189
info:
  title: DockerBackup
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/KuraiAndras/DockerBackup/blob/main/LICENSE
security: []

paths:

  /api/containers:
    get:
      summary: Get containers
      description: Get the list of containers
      operationId: GetContainers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/Container.yaml"
