// <auto-generated />
using System;
using DockerBackup.WebApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DockerBackup.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDb))]
    [Migration("20241023091406_AddBackups")]
    partial class AddBackups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DockerBackup.WebApi.Database.ContainerBackup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContainerBackups");
                });

            modelBuilder.Entity("DockerBackup.WebApi.Database.FileBackup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContainerBackupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerBackupId");

                    b.ToTable("FileBackups");
                });

            modelBuilder.Entity("DockerBackup.WebApi.Database.FileBackup", b =>
                {
                    b.HasOne("DockerBackup.WebApi.Database.ContainerBackup", "Backup")
                        .WithMany("Files")
                        .HasForeignKey("ContainerBackupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Backup");
                });

            modelBuilder.Entity("DockerBackup.WebApi.Database.ContainerBackup", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
